### PR TITLE
update actions

### PR DESCRIPTION
**Pull request by joshuafernandes**

### CODE REVIEW

**Comment by joshuafernandes** [comment]
@m4sterbunny happy to be overriden on this but think with the md lint it might be good to block the build? I can go through each repo and bring em compliant and long term it'll get to be practice?

**Comment by m4sterbunny** [comment]
Perhaps we give everyone a soft landing and revisit making it fail build in say 6 months?

**Comment by joshuafernandes** [comment]
Hi @m4sterbunny the md lint is working fine, spelling with vale throws a couple of errors that Im not sure of - you able to have a looksee please when you can. This should be good to merge after that I reckon (or with the spelling issues?)

**Review by usmansaleem — APPROVED** [review]
LGTM

**Pull request merged**
