### PR TITLE
Change Site URL for Docs

### PR DESCRIPTION
**Pull request by jlazoff**
Changing Site URL to new https://docs.eth2signer.consensys.net/en/latest/

### CODE REVIEW

**Review by NicolasMassart — APPROVED** [review]
domains are updated on rtd so looks good to me

**Review by NicolasMassart — DISMISSED** [review]
Change is ok, but as there's a broken link I noticed that software repos was renamed to https://pegasyseng.github.io/web3signer/

So it at least requires to fix this url issue, but maybe also it would be better to directly move to web3signer domain instead of making a stop by consensys eth2signer just to move to web3signer shortly after ?

**Review by joshuafernandes — APPROVED** [review]
LGTM

**Review by jlazoff — COMMENTED** [review]
Complete!

**Pull request merged**
